# Generated by Django 4.1.4 on 2023-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=1, upload_to='producto'),
            preserve_default=False,
        ),
    ]
