# Generated by Django 4.1.4 on 2023-01-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_producto_imagen_producto_disponibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponibilidad',
        ),
    ]
