# Generated by Django 4.1.4 on 2023-01-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_disponiblidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponiblidad',
        ),
    ]
